package com.fourthbutton.telematics.pds.mapper;

import java.util.UUID;

import org.apache.ibatis.annotations.Param;

import com.fourthbutton.telematics.pds.entity.DeviceProfileWithUUID;

public interface DeviceProfileWithUUIDMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * device_profile_with_uuid
     *
     * @mbggenerated Tue Jun 30 17:11:25 CST 2015
     */
    int deleteByPrimaryKey(@Param("tuId") UUID tuId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * device_profile_with_uuid
     *
     * @mbggenerated Tue Jun 30 17:11:25 CST 2015
     */
    int insert(DeviceProfileWithUUID record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * device_profile_with_uuid
     *
     * @mbggenerated Tue Jun 30 17:11:25 CST 2015
     */
    int insertSelective(DeviceProfileWithUUID record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * device_profile_with_uuid
     *
     * @mbggenerated Tue Jun 30 17:11:25 CST 2015
     */
    DeviceProfileWithUUID selectByPrimaryKey(@Param("tuId") UUID tuId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * device_profile_with_uuid
     *
     * @mbggenerated Tue Jun 30 17:11:25 CST 2015
     */
    int updateByPrimaryKeySelective(DeviceProfileWithUUID record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * device_profile_with_uuid
     *
     * @mbggenerated Tue Jun 30 17:11:25 CST 2015
     */
    int updateByPrimaryKey(DeviceProfileWithUUID record);
}
